version: "3.9"
services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB="${DATABASE_NAME}"
      - POSTGRES_USER="${DATABASE_USER}"
      - POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

volumes:
  data:
